# Generated by Django 5.1.7 on 2025-05-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis_app', '0002_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
