# Generated by Django 5.1.7 on 2025-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis_app', '0004_location_user_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
