# Generated by Django 5.1.7 on 2025-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis_app', '0004_alter_location_type_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type_client',
            field=models.CharField(choices=[('biznes', 'Biznes'), ('individ', 'Individ')], default='individ', max_length=100),
        ),
    ]
